name: Upload

on:                       # トリガーの設定
  push:                   # プッシュ時に実行
    branches: [master]    # ブランチの指定      
jobs:
  FTP-Upload-Action:
    name: FTP-Upload-Action   # ジョブの名前
    runs-on: ubuntu-latest    # 仮想環境の指定
    steps:
        - name: checkout
          uses: actions/checkout@v2   # チェックアウトアクション（https://github.com/actions/checkout）
        - name: FTP-Deploy-Action
          uses: SamKirkland/FTP-Deploy-Action@4.2.0     # FTPアップロードアクション（https://github.com/SamKirkland/FTP-Deploy-Action）
          with:
            server: ${{ secrets.SERVER }}                        # FTPの サーバーアドレス
            username: ${{ secrets.USERNAME }}                    # FTPのユーザー名名
            password: ${{ secrets.PASSWORD }}                    # FTPのパスワード
            local-dir: ./                                        # アップロードしたいファイルのパス
            server-dir: /study7980.cloudfree.jp/public_html/     # アップロード先のリモートパス
            exclude: |
              **/.git*
              **/.git*/**
              **/node_modules/**
              **/test_all/**